live_config_reload = true

import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/solarized_dark.toml"
  ]

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"


[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 2
