[font]
# size down 4 times for a nice size
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 2

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/keybindings.toml",
  # "~/.config/alacritty/kanagawa.toml"
  "~/.config/alacritty/solarized_dark.toml"
  ]
