live_config_reload: true

env:
  CSCHEME: solarized

font:
  size: 14.0

  normal:
    family: FiraCode Nerd Font
    style: Light

selection:
  save_to_clipboard: true

window:
  padding:
    x: 5
    y: 2
  decorations: buttonless

schemes:
  solarized_dark: &dark # Default colors
    primary:
      background: "0x002b36"
      foreground: "#a3afb1" # 3 tints lighter than incumbent

    # Normal colors
    normal:
      black: "0x073642"
      red: "0xdc322f"
      green: "0x859900"
      yellow: "0xb58900"
      blue: "0x268bd2"
      magenta: "0xd33682"
      cyan: "0x2aa198"
      white: "0xeee8d5"

    # Bright colors
    bright:
      black: "0x002b36"
      red: "0xcb4b16"
      green: "0x586e75"
      yellow: "0x657b83"
      blue: "0x839496"
      magenta: "0x6c71c4"
      cyan: "0x93a1a1"
      white: "0xfdf6e3"
  solarized_light: &light # Default colors
    primary:
      background: "0xfdf6e3"
      foreground: "0x586e75"

    # Normal colors
    normal:
      black: "0x073642"
      red: "0xdc322f"
      green: "0x859900"
      yellow: "0xb58900"
      blue: "0x268bd2"
      magenta: "0xd33682"
      cyan: "0x2aa198"
      white: "0xeee8d5"

    # Bright colors
    bright:
      black: "0x002b36"
      red: "0xcb4b16"
      green: "0x586e75"
      yellow: "0x657b83"
      blue: "0x839496"
      magenta: "0x6c71c4"
      cyan: "0x93a1a1"
      white: "0xfdf6e3"

  tokyo_night_storm: &storm
    primary:
      background: "0x24283b"
      foreground: "0xc0caf5"

    # Normal colors
    normal:
      black: "0x1D202F"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xa9b1d6"

    # Bright colors
    bright:
      black: "0x414868"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xc0caf5"

    indexed_colors:
      - { index: 16, color: "0xff9e64" }
      - { index: 17, color: "0xdb4b4b" }

  tokyo_night_night: &night
    primary:
      background: "0x1a1b26"
      foreground: "0xc0caf5"

    # Normal colors
    normal:
      black: "0x15161e"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xa9b1d6"

    # Bright colors
    bright:
      black: "0x414868"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xc0caf5"

    indexed_colors:
      - { index: 16, color: "0xff9e64" }
      - { index: 17, color: "0xdb4b4b" }

  kanagawa: &kanagawa
    primary:
      background: "0x1f1f28"
      foreground: "0xdcd7ba"

    normal:
      black: "0x090618"
      red: "0xc34043"
      green: "0x76946a"
      yellow: "0xc0a36e"
      blue: "0x7e9cd8"
      magenta: "0x957fb8"
      cyan: "0x6a9589"
      white: "0xc8c093"

    bright:
      black: "0x727169"
      red: "0xe82424"
      green: "0x98bb6c"
      yellow: "0xe6c384"
      blue: "0x7fb4ca"
      magenta: "0x938aa9"
      cyan: "0x7aa89f"
      white: "0xdcd7ba"

    selection:
      background: "0x2d4f67"
      foreground: "0xc8c093"

    indexed_colors:
      - { index: 16, color: "0xffa066" }
      - { index: 17, color: "0xff5d62" }

  cpnmco: &cpnmco
    primary:
      background: "#24273A" # base
      foreground: "#CAD3F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#CAD3F5" # text
      bright_foreground: "#CAD3F5" # text

    cursor:
      text: "#24273A" # base
      cursor: "#F4DBD6" # rosewater
    vi_mode_cursor:
      text: "#24273A" # base
      cursor: "#B7BDF8" # lavender

    search:
      matches:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0
      focused_match:
        foreground: "#24273A" # base
        background: "#A6DA95" # green
      footer_bar:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0

    hints:
      start:
        foreground: "#24273A" # base
        background: "#EED49F" # yellow
      end:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0

    selection:
      text: "#24273A" # base
      background: "#F4DBD6" # rosewater

    normal:
      black: "#494D64" # surface1
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#B8C0E0" # subtext1

    bright:
      black: "#5B6078" # surface2
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#A5ADCB" # subtext0

    dim:
      black: "#494D64" # surface1
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#B8C0E0" # subtext1

    indexed_colors:
      - { index: 16, color: "#F5A97F" }
      - { index: 17, color: "#F4DBD6" }

colors: *dark

key_bindings:
  ## TMUX SPECIFIC THINGSS...see https://www.joshmedeski.com/posts/macos-keyboard-shortcuts-for-tmux
  # Create a new tmux window
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Create a new vertical Split
  - { key: D, mods: Command, chars: "\x02\x25" }
  # Create a new horizontal split
  - { key: D, mods: Command|Shift, chars: "\x02\x22" }
  # Cycle to the next pane
  - { key: RBracket, mods: Command, chars: "\x02\x6f" }
    # Cycle to the previous pane (only the immediate previous)
  - { key: LBracket, mods: Command, chars: "\x02\x3b" }
  # Rename the current tmux window
  - { key: Comma, mods: Command, chars: "\x02\x2c" }
  # Zoom the current pane
  - { key: Z, mods: Command, chars: "\x02\x7a" }
  # Select a new tmux session for the attached client interactively
  - { key: P, mods: Command, chars: "\x02\x73" }
  # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
